### ISSUE TITLE
Tile maze: lemon smell on orange tile via unsteppable purple

### ISSUE THREAD

**Issue by Nokob** [Putnam3145/Putnam3145.github.io#3]
(I feel sort of weird submitting an issue to a personal website out of the blue, but… here it is)

I got a maze that looked impossible, which I ended up "solving" by going from an orange to a blue:
![image](https://cloud.githubusercontent.com/assets/1131899/12837855/87918b28-cb94-11e5-84be-adca1ac45aeb.png)

In order to do that, I first tried to go to the adjacent purple, which didn't change my position because of the red but still made me smell like lemons despite the fact that I ended up back on the orange.

(Technically I should have just stayed on the purple, since red tiles stop you altogether rather than sending you back where you came from. But I guess that's a separate issue.)

**Comment by Putnam3145** [comment]
This is actually intended. This has to be done to solve the tile puzzle in UT, though it was yellow instead of red.
On Feb 4, 2016 10:04 PM, Nokob notifications@github.com wrote:(I feel sort of weird submitting an issue to a personal website out of the blue, but… here it is)

I got a maze that looked impossible, which I ended up "solving" by going from an orange to a blue:

In order to do that, I first tried to go to the adjacent purple, which didn't change my position because of the red but still made me smell like lemons despite the fact that I ended up back on the orange

(Technically I should have just stayed on the purple, since red tiles stop you altogether rather than sending you back where you came from But I guess that's a separate issue)

**Comment by Nokob** [comment]
Reds behave differently from yellows (and blues) in the game. But even with a yellow, you shouldn't retain the lemon smell if you start and end on an orange tile.

**Comment by Putnam3145** [comment]
Tile maze is gone (for now), so this is irrelevant; I'm liable to rewrite the whole thing if it comes back
